// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFkTNV_Czendg7kuYxl6-lMdVDzcYrSw',
    appId: '1:245435050851:web:825af7f6987a327be20156',
    messagingSenderId: '245435050851',
    projectId: 'smartgist-c2320',
    authDomain: 'smartgist-c2320.firebaseapp.com',
    storageBucket: 'smartgist-c2320.appspot.com',
    measurementId: 'G-7GP6DPRSCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmBtfRUpR5cGJ7jWFfTBoGO0VFcMnNn4I',
    appId: '1:245435050851:android:d89ddb719fbd90a0e20156',
    messagingSenderId: '245435050851',
    projectId: 'smartgist-c2320',
    storageBucket: 'smartgist-c2320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdaYxD-nyXqif2Hx1qP2iIZ891dflaxA',
    appId: '1:245435050851:ios:bc7f678498b84b9de20156',
    messagingSenderId: '245435050851',
    projectId: 'smartgist-c2320',
    storageBucket: 'smartgist-c2320.appspot.com',
    iosBundleId: 'com.example.smartGist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIdaYxD-nyXqif2Hx1qP2iIZ891dflaxA',
    appId: '1:245435050851:ios:bc7f678498b84b9de20156',
    messagingSenderId: '245435050851',
    projectId: 'smartgist-c2320',
    storageBucket: 'smartgist-c2320.appspot.com',
    iosBundleId: 'com.example.smartGist',
  );

}